indexa = 'This is a sample index text'
print(indexa[0])
print(indexa[0:2])
print(indexa[0:-2])
print(indexa[:-2])
print(indexa[0:20:4])
print(indexa.find('This'))
print(indexa.find('is',3))
print(indexa.index('sample'))
print(indexa.index('is',3))